# Generated by Django 4.0.5 on 2022-07-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='deporte',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='fecha',
            field=models.DateField(max_length=30),
        ),
    ]
